package d2records

import "github.com/OpenDiablo2/OpenDiablo2/d2common/d2enum"

// https://d2mods.info/forum/kb/viewarticle?a=360

// MonStats stores all of the MonStatRecords
type MonStats map[string]*MonStatRecord

type (
	// MonStatRecord represents a single row from `data/global/excel/monstats.txt` in the MPQ files.
	// These records are used for creating monsters.
	MonStatRecord struct {
		TreasureClassQuestCompleteId   string
		Key                            string
		BaseKey                        string
		NextKey                        string
		NameString                     string
		ExtraDataKey                   string
		PropertiesKey                  string
		MonsterGroup                   string
		AiKey                          string
		DescriptionStringTableKey      string
		AnimationDirectoryToken        string
		SpawnKey                       string
		SpawnAnimationKey              string
		MinionId1                      string
		MinionId2                      string
		SoundKeyNormal                 string
		SoundKeySpecial                string
		MissileA1                      string
		MissileA2                      string
		MissileS1                      string
		MissileS2                      string
		MissileS3                      string
		MissileS4                      string
		MissileC                       string
		MissileSQ                      string
		SkillId1                       string
		SkillId2                       string
		SkillId3                       string
		SkillId4                       string
		SkillId5                       string
		SkillId6                       string
		SkillId7                       string
		SkillId8                       string
		SkillAnimation1                string
		SkillAnimation2                string
		SkillAnimation3                string
		SkillAnimation4                string
		SkillAnimation5                string
		SkillAnimation6                string
		SkillAnimation7                string
		SkillAnimation8                string
		DamageSkillId                  string
		ElementAttackMode1             string
		ElementAttackMode2             string
		ElementAttackMode3             string
		ElementType1                   string
		ElementType2                   string
		ElementType3                   string
		TreasureClassNormal            string
		TreasureClassNightmare         string
		TreasureClassHell              string
		TreasureClassChampionNormal    string
		TreasureClassChampionNightmare string
		TreasureClassChampionHell      string
		TreasureClass3UniqueNormal     string
		TreasureClass3UniqueNightmare  string
		TreasureClass3UniqueHell       string
		TreasureClassQuestNormal       string
		TreasureClassQuestNightmare    string
		TreasureClassQuestHell         string
		TreasureClassQuestTriggerId    string
		ResistanceMagicNightmare       int
		PaletteId                      int
		SpawnOffsetX                   int
		SpawnOffsetY                   int
		MinionPartyMin                 int
		MinionPartyMax                 int
		MinionGroupMin                 int
		MinionGroupMax                 int
		PopulationReductionPercent     int
		SpeedBase                      int
		SpeedRun                       int
		Rarity                         int
		LevelNormal                    int
		LevelNightmare                 int
		LevelHell                      int
		ThreatLevel                    int
		AiDelayNormal                  int
		AiDelayNightmare               int
		AiDelayHell                    int
		AiDistanceNormal               int
		AiDistanceNightmare            int
		AiDistanceHell                 int
		AiParameterNormal1             int
		AiParameterNormal2             int
		AiParameterNormal3             int
		AiParameterNormal4             int
		AiParameterNormal5             int
		AiParameterNormal6             int
		AiParameterNormal7             int
		AiParameterNormal8             int
		AiParameterNightmare1          int
		AiParameterNightmare2          int
		AiParameterNightmare3          int
		AiParameterNightmare4          int
		AiParameterNightmare5          int
		AiParameterNightmare6          int
		AiParameterNightmare7          int
		AiParameterNightmare8          int
		AiParameterHell1               int
		AiParameterHell2               int
		AiParameterHell3               int
		AiParameterHell4               int
		AiParameterHell5               int
		AiParameterHell6               int
		AiParameterHell7               int
		AiParameterHell8               int
		Alignment                      d2enum.MonsterAlignmentType
		SkillLevel1                    int
		SkillLevel2                    int
		SkillLevel3                    int
		SkillLevel4                    int
		SkillLevel5                    int
		SkillLevel6                    int
		SkillLevel7                    int
		SkillLevel8                    int
		LeechSensitivityNormal         int
		LeechSensitivityNightmare      int
		LeechSensitivityHell           int
		ColdSensitivityNormal          int
		ColdSensitivityNightmare       int
		ColdSensitivityHell            int
		ResistancePhysicalNormal       int
		ResistancePhysicalNightmare    int
		ResistancePhysicalHell         int
		ResistanceMagicNormal          int
		ID                             int
		ResistanceMagicHell            int
		ResistanceFireNormal           int
		ResistanceFireNightmare        int
		ResistanceFireHell             int
		ResistanceLightningNormal      int
		ResistanceLightningNightmare   int
		ResistanceLightningHell        int
		ResistanceColdNormal           int
		ResistanceColdNightmare        int
		ResistanceColdHell             int
		ResistancePoisonNormal         int
		ResistancePoisonNightmare      int
		ResistancePoisonHell           int
		HealthRegenPerFrame            int
		ChanceToBlockNormal            int
		ChanceToBlockNightmare         int
		ChanceToBlockHell              int
		ChanceDeadlyStrike             int
		MinHPNormal                    int
		MinHPNightmare                 int
		MinHPHell                      int
		MaxHPNormal                    int
		MaxHPNightmare                 int
		MaxHPHell                      int
		ArmorClassNormal               int
		ArmorClassNightmare            int
		ArmorClassHell                 int
		ExperienceNormal               int
		ExperienceNightmare            int
		ExperienceHell                 int
		DamageMinA1Normal              int
		DamageMinA1Nightmare           int
		DamageMinA1Hell                int
		DamageMaxA1Normal              int
		DamageMaxA1Nightmare           int
		DamageMaxA1Hell                int
		DamageMinA2Normal              int
		DamageMinA2Nightmare           int
		DamageMinA2Hell                int
		DamageMaxA2Normal              int
		DamageMaxA2Nightmare           int
		DamageMaxA2Hell                int
		DamageMinS1Normal              int
		DamageMinS1Nightmare           int
		DamageMinS1Hell                int
		DamageMaxS1Normal              int
		DamageMaxS1Nightmare           int
		DamageMaxS1Hell                int
		AttackRatingA1Normal           int
		AttackRatingA1Nightmare        int
		AttackRatingA1Hell             int
		AttackRatingA2Normal           int
		AttackRatingA2Nightmare        int
		AttackRatingA2Hell             int
		AttackRatingS1Normal           int
		AttackRatingS1Nightmare        int
		AttackRatingS1Hell             int
		ElementChance1Normal           int
		ElementChance1Nightmare        int
		ElementChance1Hell             int
		ElementChance2Normal           int
		ElementChance2Nightmare        int
		SpecialEndDeath                int
		ElementChance3Normal           int
		ElementChance3Nightmare        int
		ElementChance3Hell             int
		ElementDamageMin1Normal        int
		ElementDamageMin1Nightmare     int
		ElementDamageMin1Hell          int
		ElementDamageMin2Normal        int
		ElementDamageMin2Nightmare     int
		ElementDamageMin2Hell          int
		ElementDamageMin3Normal        int
		ElementDamageMin3Nightmare     int
		ElementDamageMin3Hell          int
		ElementDamageMax1Normal        int
		ElementDamageMax1Nightmare     int
		ElementDamageMax1Hell          int
		ElementDamageMax2Normal        int
		ElementDamageMax2Nightmare     int
		ElementDamageMax2Hell          int
		ElementDamageMax3Normal        int
		ElementDamageMax3Nightmare     int
		ElementDamageMax3Hell          int
		ElementDuration1Normal         int
		ElementDuration1Nightmare      int
		ElementDuration1Hell           int
		ElementDuration2Normal         int
		ElementDuration2Nightmare      int
		ElementDuration2Hell           int
		ElementDuration3Normal         int
		ElementDuration3Nightmare      int
		ElementDuration3Hell           int
		ElementChance2Hell             int
		Enabled                        bool
		SpawnsMinions                  bool
		IsLeader                       bool
		TransferLeadership             bool
		IsLevelSpawnable               bool
		IsMelee                        bool
		IsNpc                          bool
		IsInteractable                 bool
		IsRanged                       bool
		HasInventory                   bool
		CanEnterTown                   bool
		IsUndeadLow                    bool
		IsUndeadHigh                   bool
		IsDemon                        bool
		IsFlying                       bool
		CanOpenDoors                   bool
		IsSpecialBoss                  bool
		IsActBoss                      bool
		IsKillable                     bool
		IsAiSwitchable                 bool
		DisableAura                    bool
		DisableMultiShot               bool
		DisableCounting                bool
		IgnorePets                     bool
		DealsDamageOnDeath             bool
		GenericSpawn                   bool
		IgnoreMonLevelTxt              bool
		CanBlockWithoutShield          bool
		SpecialGetModeChart            bool
		SpecialEndGeneric              bool
		SpecialClientEnd               bool
	}
)
