package d2records

import "github.com/OpenDiablo2/OpenDiablo2/d2common/d2calculation"

// SkillDescriptions stores all of the SkillDescriptionRecords
type SkillDescriptions map[string]*SkillDescriptionRecord

// SkillDescriptionRecord is a single row from skilldesc.txt and is used for
// generating text strings for skills.
type SkillDescriptionRecord struct {
	Desccalcb3   d2calculation.Calculation
	Dsc3calca7   d2calculation.Calculation
	Dsc3calcb5   d2calculation.Calculation
	Dsc3calca5   d2calculation.Calculation
	Dsc3calcb7   d2calculation.Calculation
	Dsc3calcb4   d2calculation.Calculation
	Dsc3calcb6   d2calculation.Calculation
	Dsc3calca4   d2calculation.Calculation
	Dsc3calcb3   d2calculation.Calculation
	Dsc3calca3   d2calculation.Calculation
	Dsc3calcb2   d2calculation.Calculation
	Dsc3calca2   d2calculation.Calculation
	Dsc3calcb1   d2calculation.Calculation
	DdamCalc1    d2calculation.Calculation
	DdamCalc2    d2calculation.Calculation
	Dsc3calca1   d2calculation.Calculation
	P1dmmin      d2calculation.Calculation
	P1dmmax      d2calculation.Calculation
	Dsc2calcb4   d2calculation.Calculation
	P2dmmin      d2calculation.Calculation
	P2dmmax      d2calculation.Calculation
	Dsc2calca4   d2calculation.Calculation
	P3dmmin      d2calculation.Calculation
	P3dmmax      d2calculation.Calculation
	Dsc2calcb3   d2calculation.Calculation
	Dsc2calca3   d2calculation.Calculation
	Dsc2calcb2   d2calculation.Calculation
	Dsc2calcb1   d2calculation.Calculation
	Dsc2calca1   d2calculation.Calculation
	Desccalcb6   d2calculation.Calculation
	Desccalca6   d2calculation.Calculation
	Desccalca1   d2calculation.Calculation
	Desccalcb1   d2calculation.Calculation
	Dsc3calca6   d2calculation.Calculation
	Desccalcb5   d2calculation.Calculation
	Desccalca5   d2calculation.Calculation
	Desccalca2   d2calculation.Calculation
	Desccalcb2   d2calculation.Calculation
	Desccalcb4   d2calculation.Calculation
	Desccalca4   d2calculation.Calculation
	Dsc2calca2   d2calculation.Calculation
	Desccalca3   d2calculation.Calculation
	Desctextb3   string
	Descline4    string
	Desctexta4   string
	Desctextb4   string
	Desctexta3   string
	Descline3    string
	Descline5    string
	Desctexta5   string
	Desctextb5   string
	Desctextb2   string
	Desctexta2   string
	Descline2    string
	Desctexta6   string
	Desctextb6   string
	Desctextb1   string
	Desctexta1   string
	Dsc2line1    string
	Dsc2texta1   string
	Dsc2textb1   string
	Descline1    string
	Descmissile3 string
	Dsc2line2    string
	Dsc2texta2   string
	Dsc2textb2   string
	Descline6    string
	Descmissile2 string
	Dsc2line3    string
	Dsc2texta3   string
	Dsc2textb3   string
	Descmissile1 string
	Descatt      string
	Dsc2line4    string
	Dsc2texta4   string
	Dsc2textb4   string
	P3dmelem     string
	P2dmelem     string
	Dsc3line1    string
	Dsc3texta1   string
	Dsc3textb1   string
	P1dmelem     string
	Descdam      string
	Dsc3line2    string
	Dsc3texta2   string
	Dsc3textb2   string
	ManaKey      string
	AltKey       string
	Dsc3line3    string
	Dsc3texta3   string
	Dsc3textb3   string
	LongKey      string
	ShortKey     string
	Dsc3line4    string
	Dsc3texta4   string
	Dsc3textb4   string
	NameKey      string
	ListPool     string
	Dsc3line7    string
	Dsc3texta5   string
	Dsc3textb5   string
	Dsc3texta7   string
	Dsc3textb7   string
	Dsc3line6    string
	Dsc3texta6   string
	Dsc3textb6   string
	Name         string
	Dsc3line5    string
	ListRow      int
	SkillColumn  int
	SkillRow     int
	SkillPage    int
	IconCel      int
}
