package d2wilderness

const (
	TreeBorderSouth int = iota + 4
	TreeBorderWest
	TreeBorderNorth
	TreeBorderEast
	TreeBorderSouthWest
	TreeBorderNorthWest
	TreeBorderNorthEast
	TreeBorderSouthEast
	TreeBoxNorthEast
	TreeBoxSouthEast
	TreeBoxSouthWest
	TreeBoxNorthWest
	WallBorderWest
	WallBorderEast
	WallBorderWestFenceNorth
	WallBorderNorthWest
	WallBorderWestFenceSouth
	WallBorderNorthFenceEast
	WallBorderNorthFenceWest
	WallBoxSouthEast
	WallBorderNorthUndergroundPassageEntrance
	WallBorderWestUndergroundPassageEntrance
	WaterBorderEast
	WaterBorderWest
	WaterBridgeEast
	DirtSquareWithRocks
	FourDirtSquaresWithRocks
	FenceMaze
	RandomTreesAndWallBoxLarge
	TreeBoxNorthSouth
	ShrineWithFenceAndTrees
	RandomTreesAndWallBoxSmall
	TreeBoxWestEastWithNorthSouthPath
	TreeBoxNorthSouthWithEastWestPath
	GrassPatch1
	GrassPatch2
	EnemyFeature1
	EnemyFeature2
	EnemyFeature3
	EnemyFeature4
	EnemyFeature5
	EnemyFeature6
	Pond
	House1
	House2
	BurnedHouse
	NotTheCowLevel
	UndergroundCavern
	DenOfEvil
)
