// Code generated by "stringer -linecomment -type AnimationMode"; DO NOT EDIT.

package d2enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AnimationModePlayerDeath-0]
	_ = x[AnimationModePlayerNeutral-1]
	_ = x[AnimationModePlayerWalk-2]
	_ = x[AnimationModePlayerRun-3]
	_ = x[AnimationModePlayerGetHit-4]
	_ = x[AnimationModePlayerTownNeutral-5]
	_ = x[AnimationModePlayerTownWalk-6]
	_ = x[AnimationModePlayerAttack1-7]
	_ = x[AnimationModePlayerAttack2-8]
	_ = x[AnimationModePlayerBlock-9]
	_ = x[AnimationModePlayerCast-10]
	_ = x[AnimationModePlayerThrow-11]
	_ = x[AnimationModePlayerKick-12]
	_ = x[AnimationModePlayerSkill1-13]
	_ = x[AnimationModePlayerSkill2-14]
	_ = x[AnimationModePlayerSkill3-15]
	_ = x[AnimationModePlayerSkill4-16]
	_ = x[AnimationModePlayerDead-17]
	_ = x[AnimationModePlayerSequence-18]
	_ = x[AnimationModePlayerKnockBack-19]
	_ = x[AnimationModeMonsterDeath-20]
	_ = x[AnimationModeMonsterNeutral-21]
	_ = x[AnimationModeMonsterWalk-22]
	_ = x[AnimationModeMonsterGetHit-23]
	_ = x[AnimationModeMonsterAttack1-24]
	_ = x[AnimationModeMonsterAttack2-25]
	_ = x[AnimationModeMonsterBlock-26]
	_ = x[AnimationModeMonsterCast-27]
	_ = x[AnimationModeMonsterSkill1-28]
	_ = x[AnimationModeMonsterSkill2-29]
	_ = x[AnimationModeMonsterSkill3-30]
	_ = x[AnimationModeMonsterSkill4-31]
	_ = x[AnimationModeMonsterDead-32]
	_ = x[AnimationModeMonsterKnockback-33]
	_ = x[AnimationModeMonsterSequence-34]
	_ = x[AnimationModeMonsterRun-35]
	_ = x[AnimationModeObjectNeutral-36]
	_ = x[AnimationModeObjectOperating-37]
	_ = x[AnimationModeObjectOpened-38]
	_ = x[AnimationModeObjectSpecial1-39]
	_ = x[AnimationModeObjectSpecial2-40]
	_ = x[AnimationModeObjectSpecial3-41]
	_ = x[AnimationModeObjectSpecial4-42]
	_ = x[AnimationModeObjectSpecial5-43]
}

const _AnimationMode_name = "DTNUWLRNGHTNTWA1A2BLSCTHKKS1S2S3S4DDGHGHDTNUWLGHA1A2BLSCS1S2S3S4DDGHxxRNNUOPONS1S2S3S4S5"

var _AnimationMode_index = [...]uint8{0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88}

func (i AnimationMode) String() string {
	if i < 0 || i >= AnimationMode(len(_AnimationMode_index)-1) {
		return "AnimationMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AnimationMode_name[_AnimationMode_index[i]:_AnimationMode_index[i+1]]
}
