// Code generated by "stringer -linecomment -type DifficultyType -output difficulty_string.go"; DO NOT EDIT.

package d2enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DifficultyNormal-0]
	_ = x[DifficultyNightmare-1]
	_ = x[DifficultyHell-2]
}

const _DifficultyType_name = "normalnightmarehell"

var _DifficultyType_index = [...]uint8{0, 6, 15, 19}

func (i DifficultyType) String() string {
	if i < 0 || i >= DifficultyType(len(_DifficultyType_index)-1) {
		return "DifficultyType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DifficultyType_name[_DifficultyType_index[i]:_DifficultyType_index[i+1]]
}
