// Code generated by "stringer -linecomment -type Hero"; DO NOT EDIT.

package d2enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HeroNone-0]
	_ = x[HeroBarbarian-1]
	_ = x[HeroNecromancer-2]
	_ = x[HeroPaladin-3]
	_ = x[HeroAssassin-4]
	_ = x[HeroSorceress-5]
	_ = x[HeroAmazon-6]
	_ = x[HeroDruid-7]
}

const _Hero_name = "BarbarianNecromancerPaladinAssassinSorceressAmazonDruid"

var _Hero_index = [...]uint8{0, 0, 9, 20, 27, 35, 44, 50, 55}

func (i Hero) String() string {
	if i < 0 || i >= Hero(len(_Hero_index)-1) {
		return "Hero(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Hero_name[_Hero_index[i]:_Hero_index[i+1]]
}
