// Code generated by "stringer -linecomment -type MonsterAnimationMode -output monster_animation_mode_string.go"; DO NOT EDIT.

package d2enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MonsterAnimationModeDeath-0]
	_ = x[MonsterAnimationModeNeutral-1]
	_ = x[MonsterAnimationModeWalk-2]
	_ = x[MonsterAnimationModeGetHit-3]
	_ = x[MonsterAnimationModeAttack1-4]
	_ = x[MonsterAnimationModeAttack2-5]
	_ = x[MonsterAnimationModeBlock-6]
	_ = x[MonsterAnimationModeCast-7]
	_ = x[MonsterAnimationModeSkill1-8]
	_ = x[MonsterAnimationModeSkill2-9]
	_ = x[MonsterAnimationModeSkill3-10]
	_ = x[MonsterAnimationModeSkill4-11]
	_ = x[MonsterAnimationModeDead-12]
	_ = x[MonsterAnimationModeKnockback-13]
	_ = x[MonsterAnimationModeSequence-14]
	_ = x[MonsterAnimationModeRun-15]
}

const _MonsterAnimationMode_name = "DTNUWLGHA1A2BLSCS1S2S3S4DDGHxxRN"

var _MonsterAnimationMode_index = [...]uint8{0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32}

func (i MonsterAnimationMode) String() string {
	if i < 0 || i >= MonsterAnimationMode(len(_MonsterAnimationMode_index)-1) {
		return "MonsterAnimationMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MonsterAnimationMode_name[_MonsterAnimationMode_index[i]:_MonsterAnimationMode_index[i+1]]
}
