// Code generated by "stringer -linecomment -type PlayerAnimationMode -output player_animation_mode_string.go"; DO NOT EDIT.

package d2enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PlayerAnimationModeDeath-0]
	_ = x[PlayerAnimationModeNeutral-1]
	_ = x[PlayerAnimationModeWalk-2]
	_ = x[PlayerAnimationModeRun-3]
	_ = x[PlayerAnimationModeGetHit-4]
	_ = x[PlayerAnimationModeTownNeutral-5]
	_ = x[PlayerAnimationModeTownWalk-6]
	_ = x[PlayerAnimationModeAttack1-7]
	_ = x[PlayerAnimationModeAttack2-8]
	_ = x[PlayerAnimationModeBlock-9]
	_ = x[PlayerAnimationModeCast-10]
	_ = x[PlayerAnimationModeThrow-11]
	_ = x[PlayerAnimationModeKick-12]
	_ = x[PlayerAnimationModeSkill1-13]
	_ = x[PlayerAnimationModeSkill2-14]
	_ = x[PlayerAnimationModeSkill3-15]
	_ = x[PlayerAnimationModeSkill4-16]
	_ = x[PlayerAnimationModeDead-17]
	_ = x[PlayerAnimationModeSequence-18]
	_ = x[PlayerAnimationModeKnockBack-19]
}

const _PlayerAnimationMode_name = "DTNUWLRNGHTNTWA1A2BLSCTHKKS1S2S3S4DDGHGH"

var _PlayerAnimationMode_index = [...]uint8{0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40}

func (i PlayerAnimationMode) String() string {
	if i < 0 || i >= PlayerAnimationMode(len(_PlayerAnimationMode_index)-1) {
		return "PlayerAnimationMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PlayerAnimationMode_name[_PlayerAnimationMode_index[i]:_PlayerAnimationMode_index[i+1]]
}
