// Code generated by "stringer -linecomment -type PlayerAnimationMode"; DO NOT EDIT.

package d2enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AnimationModePlayerDeath-0]
	_ = x[AnimationModePlayerNeutral-1]
	_ = x[AnimationModePlayerWalk-2]
	_ = x[AnimationModePlayerRun-3]
	_ = x[AnimationModePlayerGetHit-4]
	_ = x[AnimationModePlayerTownNeutral-5]
	_ = x[AnimationModePlayerTownWalk-6]
	_ = x[AnimationModePlayerAttack1-7]
	_ = x[AnimationModePlayerAttack2-8]
	_ = x[AnimationModePlayerBlock-9]
	_ = x[AnimationModePlayerCast-10]
	_ = x[AnimationModePlayerThrow-11]
	_ = x[AnimationModePlayerKick-12]
	_ = x[AnimationModePlayerSkill1-13]
	_ = x[AnimationModePlayerSkill2-14]
	_ = x[AnimationModePlayerSkill3-15]
	_ = x[AnimationModePlayerSkill4-16]
	_ = x[AnimationModePlayerDead-17]
	_ = x[AnimationModePlayerSequence-18]
	_ = x[AnimationModePlayerKnockBack-19]
}

const _PlayerAnimationMode_name = "DTNUWLRNGHTNTWA1A2BLSCTHKKS1S2S3S4DDGHGH"

var _PlayerAnimationMode_index = [...]uint8{0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40}

func (i PlayerAnimationMode) String() string {
	if i < 0 || i >= PlayerAnimationMode(len(_PlayerAnimationMode_index)-1) {
		return "PlayerAnimationMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PlayerAnimationMode_name[_PlayerAnimationMode_index[i]:_PlayerAnimationMode_index[i+1]]
}
