name: 'Auto Author Assign'

on:
    pull_request_target:
        types: [opened, reopened]

jobs:
    assign-author:
        runs-on: ubuntu-latest
        steps:
            - uses: toshimaru/auto-author-assign@v1.3.3
              with:
                  repo-token: "${{ secrets.GITHUB_TOKEN }}"
